'use strict';
// Backend: standalone JS VM on the REGISTER machine model. Same sem-generated
// opcode handlers and the same versioned/encrypted image as emit-js -- only the
// machine (register file + stack pointer, optionally masked) differs. Proving
// this agrees with the interpreter completes "many machines" across machine
// MODELS, alongside emit-lua's "many languages".
const { execProgramReg } = require('../core/machine-reg');
const { decodeImage, encodeImage, derivePerm, decodeExtSource } = require('../core/image');
const { OPS } = require('../core/spec');
const { jsHandler, jsBody } = require('../core/codegen');

// In-process register-machine runner (a conformance backend + oracle peer).
// Handlers cached but rebuilt if the ISA grew (plugin-registered opcode).
let _cache = null, _len = -1;
function handlers() {
  if (_len !== OPS.length) { _cache = OPS.map((o) => new Function('F', jsBody(o.sem))); _len = OPS.length; } // eslint-disable-line no-new-func
  return _cache;
}
function interpretReg(image, opts = {}) { return execProgramReg(image, handlers(), opts); }

function emitJsReg(image, opts = {}) {
  const bytes = encodeImage(image, opts);
  const b64 = Buffer.from(bytes).toString('base64');
  const extArg = decodeExtSource(opts); // '' for built-in cipher/integrity
  const execArr = '[\n' + OPS.map((o) => '    ' + jsHandler(o.sem)).join(',\n') + '\n  ]';
  const enc = opts.encrypted ? 'true' : 'false';
  const seed = (opts.seed !== undefined ? opts.seed : 0x2545f491) >>> 0;
  const banner = opts.banner === false ? '' : '// Generated by Prism -- standalone register-machine VM.\n';
  return `${banner}'use strict';
(function () {
  var IMAGE_B64 = ${JSON.stringify(b64)};
  function b64bytes(s) {
    if (typeof Buffer !== 'undefined') return Array.prototype.slice.call(Buffer.from(s, 'base64'));
    var bin = (typeof atob !== 'undefined') ? atob(s) : '';
    var a = []; for (var i = 0; i < bin.length; i++) a.push(bin.charCodeAt(i)); return a;
  }
  var execById = ${execArr};
  var decodeImage = ${decodeImage.toString()};
  var derivePerm = ${derivePerm.toString()};
  var execProgramReg = ${execProgramReg.toString()};
  var __out = function (s) {
    if (typeof process !== 'undefined' && process.stdout) process.stdout.write(s + '\\n');
    else if (typeof console !== 'undefined') console.log(s);
  };
  try {
    var IMAGE = decodeImage(b64bytes(IMAGE_B64)${extArg});
    var handlers = execById;
    if (IMAGE.flags & 2) { var perm = derivePerm(IMAGE.keySeed, execById.length); var byPerm = new Array(execById.length); for (var hi = 0; hi < execById.length; hi++) byPerm[perm[hi]] = execById[hi]; handlers = byPerm; }
    execProgramReg(IMAGE, handlers, { print: __out, encrypted: ${enc}, seed: ${seed} });
  } catch (e) {
    if (typeof console !== 'undefined') console.error('[prism] ' + (e && e.message ? e.message : e));
    if (typeof process !== 'undefined' && process.exit) process.exit(1);
  }
})();
`;
}

module.exports = { emitJsReg, interpretReg };
