'use strict';
// Backend: standalone Python VM -- generated from the SAME opcode spec as the JS
// and Lua backends. Each opcode's handler body is lowered from its `sem` by the
// shared codegen (pyLines); the value model lives in a Python facade `F` that
// mirrors the machine facade the other backends use. This is a THIRD target
// language proving "one spec, many machines": no hand-written, drift-prone
// semantics -- fix an opcode once and Python moves in lock-step with JS and Lua.
//
// (Like the Lua target, the image ships as native literals rather than the binary
// image + decoder, which are JS-embedded features -- noted, not hidden.)
const { OPS } = require('../core/spec');
const { pyLines } = require('../core/codegen');

function pyStr(s) { return JSON.stringify(s); } // JSON string literals are valid Python str literals
function pyConst(v) {
  if (v === null) return 'NULL';
  if (v === true) return 'True';
  if (v === false) return 'False';
  if (typeof v === 'number') return String(v);
  return pyStr(v);
}

function emitPy(image, opts = {}) {
  const consts = 'consts = [' + image.consts.map(pyConst).join(', ') + ']';
  const fns = 'fns = [\n  ' + image.functions.map((f) =>
    `{'nparams': ${f.nparams}, 'nlocals': ${f.nlocals}, 'code': [${f.code.join(', ')}], `
    + `'upvals': [${(f.upvals || []).map((u) => `{'fromLocal': ${u.fromLocal ? 'True' : 'False'}, 'index': ${u.index}}`).join(', ')}]}`
  ).join(',\n  ') + ']';
  const handlers = OPS.map((o, i) => {
    const lines = pyLines(o.sem);
    const body = lines.length ? lines.map((l) => '    ' + l).join('\n') : '    pass';
    return `def _h${i}(F):\n${body}`;
  }).join('\n');
  const table = 'HANDLERS = [' + OPS.map((o, i) => '_h' + i).join(', ') + ']';

  const banner = opts.banner === false ? '' : '# Generated by Prism -- standalone Python VM, one spec, many machines.\n';
  return `${banner}import math

NULL = object()

class Cell:
    __slots__ = ('v',)
    def __init__(self, v=NULL):
        self.v = v

${consts}
${fns}

def _numstr(v):
    if isinstance(v, int): return str(v)
    if v != v: return 'NaN'
    if v == float('inf'): return 'Infinity'
    if v == float('-inf'): return '-Infinity'
    if v.is_integer(): return str(int(v))
    return repr(v)

def toStr(v):
    if v is NULL or v is None: return 'null'
    if v is True: return 'true'
    if v is False: return 'false'
    if isinstance(v, list): return '[' + ', '.join(toStr(x) for x in v) + ']'
    if isinstance(v, dict):
        if v.get('__closure'): return 'function'
        return '{' + ', '.join(str(k) + ': ' + toStr(val) for k, val in v.items()) + '}'
    if isinstance(v, (int, float)): return _numstr(v)
    return str(v)

class VM:
    def __init__(self):
        self.stack = []
        self.frames = []
        self.out = []
        self.running = True
        self.code = fns[0]['code']
        self.ip = 0
        self.locals = [Cell() for _ in range(fns[0]['nlocals'])]
        self.upvals = []
    # stack
    def pop(self): return self.stack.pop()
    def push(self, v): self.stack.append(v)
    def peek(self): return self.stack[-1]
    # operand fetch
    def u16(self):
        lo = self.code[self.ip]; hi = self.code[self.ip + 1]; self.ip += 2; return lo | (hi << 8)
    def u8(self):
        b = self.code[self.ip]; self.ip += 1; return b
    # storage
    def getConst(self, i): return consts[i]
    def getLocal(self, i): return self.locals[i].v
    def setLocal(self, i, v): self.locals[i].v = v
    def getUpval(self, i): return self.upvals[i].v
    def setUpval(self, i, v): self.upvals[i].v = v
    def makeClosure(self, fnIdx):
        desc = fns[fnIdx]['upvals']
        ups = [self.locals[d['index']] if d['fromLocal'] else self.upvals[d['index']] for d in desc]
        return {'__closure': True, 'fn': fnIdx, 'upvals': ups}
    def callValue(self, argc):
        av = [NULL] * argc
        for k in range(argc - 1, -1, -1): av[k] = self.pop()
        callee = self.pop()
        if not isinstance(callee, dict) or not callee.get('__closure'):
            raise RuntimeError('value is not callable: ' + toStr(callee))
        fn = fns[callee['fn']]
        locals_ = [Cell() for _ in range(fn['nlocals'])]
        for j in range(min(argc, fn['nparams'])): locals_[j].v = av[j]
        self.frames.append((self.code, self.ip, self.locals, self.upvals))
        self.code, self.ip, self.locals, self.upvals = fn['code'], 0, locals_, callee['upvals']
    def setIp(self, a): self.ip = a
    # value operations
    def add(self, a, b):
        an = isinstance(a, (int, float)) and not isinstance(a, bool)
        bn = isinstance(b, (int, float)) and not isinstance(b, bool)
        if an and bn: return a + b
        return toStr(a) + toStr(b)
    def sub(self, a, b): return a - b
    def mul(self, a, b): return a * b
    def div(self, a, b): return a / b
    def mod(self, a, b): return math.fmod(a, b)
    def neg(self, a): return -a
    def eq(self, a, b):
        if isinstance(a, bool) or isinstance(b, bool): return a is b
        return a == b
    def lt(self, a, b): return a < b
    def truthy(self, v):
        if v is NULL or v is None or v is False: return False
        if isinstance(v, (int, float)) and not isinstance(v, bool):
            if v != v: return False
            return v != 0
        if v == '': return False
        return True
    def print(self, v): self.out.append(toStr(v))
    # array / object value model
    def newArray(self, count):
        arr = [NULL] * count
        for k in range(count - 1, -1, -1): arr[k] = self.pop()
        return arr
    def newObject(self, count):
        pairs = []
        for _ in range(count):
            vv = self.pop(); kk = self.pop(); pairs.append((kk, vv))
        pairs.reverse()
        o = {}
        for kk, vv in pairs: o[kk] = vv
        return o
    def _idx(self, a, i):
        if isinstance(i, float) and i.is_integer(): return int(i)
        return i
    def indexGet(self, a, i):
        if a is NULL or a is None: return NULL
        if isinstance(a, list):
            i = self._idx(a, i)
            return a[i] if isinstance(i, int) and 0 <= i < len(a) else NULL
        if isinstance(a, str):
            i = self._idx(a, i)
            return a[i] if isinstance(i, int) and 0 <= i < len(a) else NULL
        if isinstance(a, dict):
            return a[i] if i in a else NULL
        return NULL
    def indexSet(self, a, i, v):
        if a is NULL or a is None: return
        if isinstance(a, list):
            i = self._idx(a, i)
            if isinstance(i, int):
                while len(a) <= i: a.append(NULL)
                a[i] = v
        elif isinstance(a, dict):
            a[i] = v
    def len(self, a):
        if isinstance(a, (list, str)): return len(a)
        return 0
    def host(self, name, count):
        args = [NULL] * count
        for k in range(count - 1, -1, -1): args[k] = self.pop()
        a = args[0] if count > 0 else NULL
        b = args[1] if count > 1 else NULL
        if name == 'floor': return math.floor(a)
        if name == 'ceil': return math.ceil(a)
        if name == 'round': return math.floor(a + 0.5)
        if name == 'abs': return abs(a)
        if name == 'sqrt': return math.sqrt(a)
        if name == 'pow': return a ** b
        if name == 'min':
            m = args[0]
            for i in range(1, count):
                if args[i] < m: m = args[i]
            return m
        if name == 'max':
            m = args[0]
            for i in range(1, count):
                if args[i] > m: m = args[i]
            return m
        if name == 'num': return a if isinstance(a, (int, float)) else float(a)
        if name == 'str': return toStr(a)
        raise RuntimeError('unknown host function: ' + name)
    def halt(self): self.running = False
    def call(self, fnIdx, argc):
        fn = fns[fnIdx]
        locals_ = [Cell() for _ in range(fn['nlocals'])]
        av = [NULL] * argc
        for k in range(argc - 1, -1, -1): av[k] = self.pop()
        for j in range(min(argc, fn['nparams'])): locals_[j].v = av[j]
        self.frames.append((self.code, self.ip, self.locals, self.upvals))
        self.code, self.ip, self.locals, self.upvals = fn['code'], 0, locals_, []
    def ret(self):
        rv = self.pop()
        if not self.frames:
            self.running = False; self.push(rv); return
        self.code, self.ip, self.locals, self.upvals = self.frames.pop()
        self.push(rv)

${handlers}
${table}

def main():
    F = VM()
    while F.running:
        op = F.code[F.ip]; F.ip += 1
        HANDLERS[op](F)
    return F.out

if __name__ == '__main__':
    for line in main():
        print(line)
`;
}

module.exports = { emitPy };
