'use strict';
// Backend: standalone JavaScript VM. Generated from the SAME opcode spec and the
// SAME machine as the interpreter -- each opcode's `exec` and the dispatch loop
// are embedded verbatim (via Function.prototype.toString). The program ships as a
// VERSIONED, integrity-checked, constant-encrypted binary image (src/core/image.js),
// decoded at load by the embedded decoder -- so the artifact carries protected
// bytes, verifies its own integrity, and refuses a tampered image.
const { execProgram } = require('../core/machine');
const { decodeImage, encodeImage, derivePerm, decodeExtSource } = require('../core/image');
const { OPS } = require('../core/spec');
const { jsHandler } = require('../core/codegen');

function emitJs(image, opts = {}) {
  const bytes = encodeImage(image, opts);
  const b64 = Buffer.from(bytes).toString('base64');
  const extArg = decodeExtSource(opts); // '' for built-in cipher/integrity
  const execArr = '[\n' + OPS.map((o) => '    /* ' + o.name + ' */ ' + jsHandler(o.sem)).join(',\n') + '\n  ]';
  const banner = opts.banner === false ? '' :
    '// Generated by Prism -- standalone VM. Versioned, integrity-checked, constant-encrypted image.\n';
  return `${banner}'use strict';
(function () {
  var IMAGE_B64 = ${JSON.stringify(b64)};
  function b64bytes(s) {
    if (typeof Buffer !== 'undefined') return Array.prototype.slice.call(Buffer.from(s, 'base64'));
    var bin = (typeof atob !== 'undefined') ? atob(s) : '';
    var a = []; for (var i = 0; i < bin.length; i++) a.push(bin.charCodeAt(i)); return a;
  }
  var execById = ${execArr};
  var decodeImage = ${decodeImage.toString()};
  var derivePerm = ${derivePerm.toString()};
  var execProgram = ${execProgram.toString()};
  var __out = function (s) {
    if (typeof process !== 'undefined' && process.stdout) process.stdout.write(s + '\\n');
    else if (typeof console !== 'undefined') console.log(s);
  };
  try {
    var IMAGE = decodeImage(b64bytes(IMAGE_B64)${extArg});
    var handlers = execById;
    if (IMAGE.flags & 2) { var perm = derivePerm(IMAGE.keySeed, execById.length); var byPerm = new Array(execById.length); for (var hi = 0; hi < execById.length; hi++) byPerm[perm[hi]] = execById[hi]; handlers = byPerm; }
    execProgram(IMAGE, handlers, { print: __out });
  } catch (e) {
    if (typeof console !== 'undefined') console.error('[prism] ' + (e && e.message ? e.message : e));
    if (typeof process !== 'undefined' && process.exit) process.exit(1);
  }
})();
`;
}

module.exports = { emitJs };
