'use strict';
// Backend: standalone Lua VM -- generated from the SAME opcode spec as the JS
// backends. The dispatch is an if/elseif chain whose handler bodies are lowered
// from each opcode's `sem` by the shared codegen (luaBody). Proving this backend
// agrees with the interpreter is the whole "one spec, many machines" thesis:
// a second target LANGUAGE with zero hand-written, drift-prone semantics.
//
// (The versioned binary image + const cipher are JS-embedded features; the Lua
// target emits the image as Lua tables directly for now -- noted, not hidden.)
const { OPS } = require('../core/spec');
const { luaBody } = require('../core/codegen');

function luaStr(s) {
  let o = '"';
  for (const ch of s) {
    const c = ch.charCodeAt(0);
    if (ch === '"') o += '\\"';
    else if (ch === '\\') o += '\\\\';
    else if (ch === '\n') o += '\\n';
    else if (ch === '\t') o += '\\t';
    else if (ch === '\r') o += '\\r';
    else if (c < 32) o += '\\' + c;
    else o += ch;
  }
  return o + '"';
}
function luaNum(n) { return Number.isInteger(n) ? String(n) : String(n); }
function luaConst(v) {
  if (v === null) return 'NULL';
  if (v === true) return 'true';
  if (v === false) return 'false';
  if (typeof v === 'number') return luaNum(v);
  return luaStr(v);
}
function luaArray0(items) { return '{' + items.map((x, i) => '[' + i + ']=' + x).join(', ') + '}'; }

function emitLua(image, opts = {}) {
  const consts = luaArray0(image.consts.map(luaConst));
  const luaUpvals = (ups) => '{n=' + ups.length + ups.map((u, ui) => ', [' + ui + ']={fromLocal=' + (u.fromLocal ? 'true' : 'false') + ', index=' + u.index + '}').join('') + '}';
  const fns = '{' + image.functions.map((f, i) =>
    '[' + i + ']={nparams=' + f.nparams + ', nlocals=' + f.nlocals + ', code=' + luaArray0(f.code.map(String)) + ', upvals=' + luaUpvals(f.upvals || []) + '}'
  ).join(', ') + '}';
  const dispatch = OPS.map((o, i) => (i === 0 ? 'if' : 'elseif') + ' op == ' + i + ' then ' + luaBody(o.sem)).join('\n      ');

  const banner = opts.banner === false ? '' : '-- Generated by Prism -- standalone Lua VM, one spec, many machines.\n';
  return `${banner}local function main()
  local NULL = {}
  local consts = ${consts}
  local fns = ${fns}
  local out = {}
  local function toStr(v)
    if v == nil or v == NULL then return 'null' end
    if v == true then return 'true' end
    if v == false then return 'false' end
    if type(v) == 'table' then
      if v.__closure then return 'function' end
      if v.__obj then
        local parts = {}
        local kk = v.__keys
        for idx = 0, kk.n - 1 do local key = kk[idx]; parts[#parts + 1] = key .. ': ' .. toStr(v[key]) end
        return '{' .. table.concat(parts, ', ') .. '}'
      end
      local parts = {}
      for k = 0, (v.n or 0) - 1 do parts[#parts + 1] = toStr(v[k]) end
      return '[' .. table.concat(parts, ', ') .. ']'
    end
    if type(v) == 'number' then
      if v == math.floor(v) and v < 9007199254740992 and v > -9007199254740992 then return string.format('%d', v) end
      return tostring(v)
    end
    return tostring(v)
  end
  local stack, sp = {}, 0
  local frames, fp = {}, 0
  local function mkLocals(n) local t = {}; for i = 0, n - 1 do t[i] = { v = NULL } end; return t end
  local frame = { code = fns[0].code, ip = 0, locals = mkLocals(fns[0].nlocals), upvals = {} }
  local running = true
  local F = {}
  F.pop = function() local v = stack[sp]; stack[sp] = nil; sp = sp - 1; return v end
  F.push = function(v) sp = sp + 1; stack[sp] = v end
  F.peek = function() return stack[sp] end
  F.u16 = function() local lo = frame.code[frame.ip]; local hi = frame.code[frame.ip + 1]; frame.ip = frame.ip + 2; return lo + hi * 256 end
  F.u8 = function() local b = frame.code[frame.ip]; frame.ip = frame.ip + 1; return b end
  F.getConst = function(i) return consts[i] end
  F.getLocal = function(i) return frame.locals[i].v end
  F.setLocal = function(i, v) frame.locals[i].v = v end
  F.getUpval = function(i) return frame.upvals[i].v end
  F.setUpval = function(i, v) frame.upvals[i].v = v end
  F.makeClosure = function(fnIdx)
    local desc = fns[fnIdx].upvals or {}
    local ups = {}
    for k = 0, (desc.n or #desc) - 1 do
      local d = desc[k]
      ups[k] = d.fromLocal and frame.locals[d.index] or frame.upvals[d.index]
    end
    return { __closure = true, fn = fnIdx, upvals = ups }
  end
  F.callValue = function(argc)
    local av = {}
    for k = argc - 1, 0, -1 do av[k] = F.pop() end
    local callee = F.pop()
    if type(callee) ~= 'table' or not callee.__closure then error('value is not callable') end
    local fn = fns[callee.fn]
    local locals = mkLocals(fn.nlocals)
    for j = 0, math.min(argc, fn.nparams) - 1 do locals[j].v = av[j] end
    fp = fp + 1; frames[fp] = frame
    frame = { code = fn.code, ip = 0, locals = locals, upvals = callee.upvals }
  end
  F.setIp = function(a) frame.ip = a end
  F.add = function(a, b) if type(a) == 'number' and type(b) == 'number' then return a + b else return toStr(a) .. toStr(b) end end
  F.sub = function(a, b) return a - b end
  F.mul = function(a, b) return a * b end
  F.div = function(a, b) return a / b end
  F.mod = function(a, b) return a % b end
  F.neg = function(a) return -a end
  F.eq = function(a, b) return a == b end
  F.lt = function(a, b) return a < b end
  F.truthy = function(v)
    if v == nil or v == NULL or v == false or v == 0 or v == '' then return false end
    if type(v) == 'number' and v ~= v then return false end
    return true
  end
  F.print = function(v) out[#out + 1] = toStr(v) end
  F.newArray = function(count) local arr = { n = count }; for k = count - 1, 0, -1 do arr[k] = F.pop() end; return arr end
  F.newObject = function(count)
    local ps = {}
    for k = 1, count do local v = F.pop(); local key = F.pop(); ps[#ps + 1] = { key, v } end
    local obj = { __obj = true, __keys = { n = 0 } }
    for k = #ps, 1, -1 do
      local key, v = ps[k][1], ps[k][2]
      if obj[key] == nil then local kk = obj.__keys; kk[kk.n] = key; kk.n = kk.n + 1 end
      obj[key] = v
    end
    return obj
  end
  F.indexGet = function(a, i)
    if type(a) == 'table' and a ~= NULL then local v = a[i]; if v == nil then return NULL end; return v
    elseif type(a) == 'string' then return string.sub(a, i + 1, i + 1)
    else return NULL end
  end
  F.indexSet = function(a, i, v)
    if type(a) ~= 'table' or a == NULL then return end
    if a.__obj then
      if a[i] == nil then local kk = a.__keys; kk[kk.n] = i; kk.n = kk.n + 1 end
      a[i] = v
    else
      a[i] = v; if a.n == nil or i >= a.n then a.n = i + 1 end
    end
  end
  F.len = function(a)
    if type(a) == 'table' and a ~= NULL then return a.n or 0
    elseif type(a) == 'string' then return #a
    else return 0 end
  end
  F.host = function(name, count)
    local args = {}
    for k = count - 1, 0, -1 do args[k] = F.pop() end
    local a, b = args[0], args[1]
    if name == 'floor' then return math.floor(a)
    elseif name == 'ceil' then return math.ceil(a)
    elseif name == 'round' then return math.floor(a + 0.5)
    elseif name == 'abs' then return math.abs(a)
    elseif name == 'sqrt' then return math.sqrt(a)
    elseif name == 'pow' then return a ^ b
    elseif name == 'min' then local m = args[0]; for i = 1, count - 1 do if args[i] < m then m = args[i] end end; return m
    elseif name == 'max' then local m = args[0]; for i = 1, count - 1 do if args[i] > m then m = args[i] end end; return m
    elseif name == 'num' then return tonumber(a)
    elseif name == 'str' then return toStr(a)
    else error('unknown host function: ' .. name) end
  end
  F.halt = function() running = false end
  F.call = function(fnIdx, argc)
    local fn = fns[fnIdx]
    local av = {}
    for k = argc - 1, 0, -1 do av[k] = F.pop() end
    local locals = mkLocals(fn.nlocals)
    for j = 0, math.min(argc, fn.nparams) - 1 do locals[j].v = av[j] end
    fp = fp + 1; frames[fp] = frame
    frame = { code = fn.code, ip = 0, locals = locals, upvals = {} }
  end
  F.ret = function()
    local rv = F.pop()
    if fp == 0 then running = false; F.push(rv); return end
    frame = frames[fp]; frames[fp] = nil; fp = fp - 1
    F.push(rv)
  end
  while running do
    local op = frame.code[frame.ip]; frame.ip = frame.ip + 1
    ${dispatch}
    else error('illegal opcode ' .. tostring(op)) end
  end
  return out
end
local out = main()
for i = 1, #out do print(out[i]) end
`;
}

module.exports = { emitLua };
