// Generated by Prism -- standalone VM. Versioned, integrity-checked, constant-encrypted image.
'use strict';
(function () {
  var IMAGE_B64 = "UFIBAAGR9EUlOLQNPAMAIQAAAC+l/TUH2c2DH3GGYUiKtLVn5SRjZvj9yAC0ChwVOTmIpgIAAAEAGAABAAAIAAABAQAHAAAJGwECABkBAAEbBBoBAQAKAAcAAAcAAAsaBBo=";
  function b64bytes(s) {
    if (typeof Buffer !== 'undefined') return Array.prototype.slice.call(Buffer.from(s, 'base64'));
    var bin = (typeof atob !== 'undefined') ? atob(s) : '';
    var a = []; for (var i = 0; i < bin.length; i++) a.push(bin.charCodeAt(i)); return a;
  }
  var execById = [
    /* HALT */ (F) => { F.halt(); },
    /* PUSH_CONST */ (F) => { F.push(F.getConst(F.u16())); },
    /* PUSH_TRUE */ (F) => { F.push(true); },
    /* PUSH_FALSE */ (F) => { F.push(false); },
    /* PUSH_NULL */ (F) => { F.push(null); },
    /* POP */ (F) => { F.pop(); },
    /* DUP */ (F) => { F.push(F.peek()); },
    /* LOAD */ (F) => { F.push(F.getLocal(F.u16())); },
    /* STORE */ (F) => { F.setLocal(F.u16(), F.pop()); },
    /* ADD */ (F) => { const b = F.pop(), a = F.pop(); F.push(F.add(a, b)); },
    /* SUB */ (F) => { const b = F.pop(), a = F.pop(); F.push(F.sub(a, b)); },
    /* MUL */ (F) => { const b = F.pop(), a = F.pop(); F.push(F.mul(a, b)); },
    /* DIV */ (F) => { const b = F.pop(), a = F.pop(); F.push(F.div(a, b)); },
    /* MOD */ (F) => { const b = F.pop(), a = F.pop(); F.push(F.mod(a, b)); },
    /* NEG */ (F) => { F.push(F.neg(F.pop())); },
    /* NOT */ (F) => { F.push(!F.truthy(F.pop())); },
    /* EQ */ (F) => { const b = F.pop(), a = F.pop(); F.push(F.eq(a, b)); },
    /* NE */ (F) => { const b = F.pop(), a = F.pop(); F.push(!F.eq(a, b)); },
    /* LT */ (F) => { const b = F.pop(), a = F.pop(); F.push(F.lt(a, b)); },
    /* GT */ (F) => { const b = F.pop(), a = F.pop(); F.push(F.lt(b, a)); },
    /* LE */ (F) => { const b = F.pop(), a = F.pop(); F.push(!F.lt(b, a)); },
    /* GE */ (F) => { const b = F.pop(), a = F.pop(); F.push(!F.lt(a, b)); },
    /* JMP */ (F) => { F.setIp(F.u16()); },
    /* JZ */ (F) => { const a = F.u16(); if (!F.truthy(F.pop())) F.setIp(a); },
    /* JNZ */ (F) => { const a = F.u16(); if (F.truthy(F.pop())) F.setIp(a); },
    /* CALL */ (F) => { const fn = F.u16(), argc = F.u8(); F.call(fn, argc); },
    /* RET */ (F) => { F.ret(); },
    /* PRINT */ (F) => { F.print(F.pop()); }
  ];
  var decodeImage = function decodeImage(bytes) {
  function u16(o) { return bytes[o] | (bytes[o + 1] << 8); }
  function u32(o) { return (bytes[o] | (bytes[o + 1] << 8) | (bytes[o + 2] << 16) | (bytes[o + 3] << 24)) >>> 0; }
  if (bytes[0] !== 0x50 || bytes[1] !== 0x52) throw new Error('bad magic');
  var major = bytes[2];
  if (major !== 1) throw new Error('unsupported image format ' + major); // migration seam: dispatch here
  var flags = bytes[4];
  var keySeed = u32(5);
  var checksum = u32(9);
  var h = 0x811c9dc5 >>> 0;
  for (var m = 2; m <= 8; m++) { h = (h ^ bytes[m]) >>> 0; h = Math.imul(h, 0x01000193) >>> 0; } // header meta
  for (var i = 13; i < bytes.length; i++) { h = (h ^ bytes[i]) >>> 0; h = Math.imul(h, 0x01000193) >>> 0; } // body
  if (h !== checksum) throw new Error('integrity check failed: image tampered');

  var p = 13;
  var nconsts = u16(p); p += 2;
  var constLen = u32(p); p += 4;
  var cb = bytes.slice(p, p + constLen); p += constLen;
  if (flags & 1) {
    var s = (keySeed ^ 0x9e3779b9) >>> 0;
    for (var j = 0; j < cb.length; j++) { s = (Math.imul(s, 1664525) + 1013904223) >>> 0; cb[j] = (cb[j] ^ (s >>> 24)) & 0xff; }
  }
  var consts = [];
  var cp = 0;
  var dv = new DataView(new ArrayBuffer(8));
  while (consts.length < nconsts) {
    var tag = cb[cp++];
    if (tag === 0) { for (var b = 0; b < 8; b++) dv.setUint8(b, cb[cp++]); consts.push(dv.getFloat64(0, true)); }
    else if (tag === 1) { var ln = cb[cp] | (cb[cp + 1] << 8); cp += 2; var raw = ''; for (var k = 0; k < ln; k++) raw += String.fromCharCode(cb[cp++]); consts.push(decodeURIComponent(escape(raw))); }
    else if (tag === 2) consts.push(true);
    else if (tag === 3) consts.push(false);
    else consts.push(null);
  }
  var nfns = u16(p); p += 2;
  var functions = [];
  for (var f = 0; f < nfns; f++) {
    var nparams = bytes[p++];
    var nlocals = u16(p); p += 2;
    var codeLen = u16(p); p += 2;
    var code = [];
    for (var c = 0; c < codeLen; c++) code.push(bytes[p++]);
    functions.push({ nparams: nparams, nlocals: nlocals, code: code });
  }
  return { consts: consts, functions: functions, entry: 0 };
};
  var execProgram = function execProgram(image, execById, opts) {
  opts = opts || {};
  const out = [];
  const print = opts.print || function (s) { out.push(String(s)); };
  const fns = image.functions;
  const consts = image.consts;
  const stack = [];
  let frames = [];
  let frame = { code: fns[0].code, ip: 0, locals: new Array(fns[0].nlocals).fill(null) };
  let running = true;

  const toStr = function (v) {
    if (v === null || v === undefined) return 'null';
    if (v === true) return 'true';
    if (v === false) return 'false';
    return String(v);
  };

  const F = {
    // stack
    pop: function () { return stack.pop(); },
    push: function (v) { stack.push(v); },
    peek: function () { return stack[stack.length - 1]; },
    // operand fetch (advances the current frame's ip)
    u16: function () { const lo = frame.code[frame.ip++], hi = frame.code[frame.ip++]; return lo | (hi << 8); },
    u8: function () { return frame.code[frame.ip++]; },
    // storage
    getConst: function (i) { return consts[i]; },
    getLocal: function (i) { return frame.locals[i]; },
    setLocal: function (i, v) { frame.locals[i] = v; },
    setIp: function (a) { frame.ip = a; },
    // value operations (the whole numeric/string semantics live here)
    add: function (a, b) { return (typeof a === 'number' && typeof b === 'number') ? a + b : toStr(a) + toStr(b); },
    sub: function (a, b) { return a - b; },
    mul: function (a, b) { return a * b; },
    div: function (a, b) { return a / b; },
    mod: function (a, b) { return a % b; },
    neg: function (a) { return -a; },
    eq: function (a, b) { return a === b; },
    lt: function (a, b) { return a < b; },
    truthy: function (v) { return !(v === null || v === undefined || v === false || v === 0 || v === '' || (typeof v === 'number' && isNaN(v))); },
    toStr: toStr,
    print: function (v) { print(toStr(v)); },
    halt: function () { running = false; },
    // calls
    call: function (fnIdx, argc) {
      const fn = fns[fnIdx];
      const locals = new Array(fn.nlocals).fill(null);
      for (let k = argc - 1; k >= 0; k--) locals[k] = stack.pop();
      frames.push(frame);
      frame = { code: fn.code, ip: 0, locals: locals };
    },
    ret: function () {
      const rv = stack.pop();
      if (frames.length === 0) { running = false; stack.push(rv); return; }
      frame = frames.pop();
      stack.push(rv);
    },
  };

  let steps = 0;
  const MAX = opts.maxSteps || 20000000;
  while (running) {
    if (++steps > MAX) throw new Error('resource limit: instruction budget exceeded');
    const op = frame.code[frame.ip++];
    const ex = execById[op];
    if (!ex) throw new Error('illegal opcode ' + op + ' at ip=' + (frame.ip - 1));
    ex(F);
  }
  return { output: out, steps: steps };
};
  var __out = function (s) {
    if (typeof process !== 'undefined' && process.stdout) process.stdout.write(s + '\n');
    else if (typeof console !== 'undefined') console.log(s);
  };
  try {
    var IMAGE = decodeImage(b64bytes(IMAGE_B64));
    execProgram(IMAGE, execById, { print: __out });
  } catch (e) {
    if (typeof console !== 'undefined') console.error('[prism] ' + (e && e.message ? e.message : e));
    if (typeof process !== 'undefined' && process.exit) process.exit(1);
  }
})();
